import Footer from './components/Footer'
import Nav from './components/Nav'
import './globals.css'
import {Mulish } from 'next/font/google'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const  mulish = Mulish({
  weight:'400',
  subsets:['latin'],
  display:'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={mulish.className}>

      <Nav/>      
      {children}
      <Footer/>
        </body>
      
    </html>
  )
}
